### ISSUE TITLE
Invalid state transition during node delete

### ISSUE THREAD

**Issue by cameronbrunner** [UnivaCorporation/tortuga#321] opened 2018-08-21 16:11 UTC
I had a node transition to Unresponsive while it was being deleted.  This ended up affecting the deletion of the node in that it would not leave the 'Unresponsive' state without another call to delete node.

@dtougas

**Comment by dtougas** [comment] 2018-12-31 15:14
This is tricky. We don't keep track anywhere of what pending operations are happening to a node. As a result, the process that is responsible for setting the Unresponsive state will not have a way to check if the node is in the middle of the provisioning or deleting process.

**Comment by dtougas** [comment] 2018-12-31 15:18
This is a duplicate of #216.

**Closed by dtougas** 2018-12-31 15:18 UTC
